version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DSN=web:12345@tcp(mysql:3306)/snippetbox?parseTime=true
      - COOKIE_SECURE=false
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: